language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t volkovd/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true volkovd/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-827030425344"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"